apiVersion: v1
kind: Service
metadata:
  name: server-manual
  namespace: default
spec:
  ports:
  - name: http
    port: 7071
    targetPort: 8080
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: server-manual-1
  namespace: default
  labels:
    kubernetes.io/service-name: server-manual
addressType: IPv4
ports:
- name: http
  port: 8080
  protocol: TCP
endpoints:
- addresses:
  - 10.10.10.10
  conditions:
    ready: true
